# Generated by Django 3.2.4 on 2021-06-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_desc', models.CharField(max_length=200)),
                ('event_pic', models.FileField(blank=True, default='defaultpic.jpg', upload_to='img/')),
                ('event_date', models.DateField(blank=True)),
                ('event_time', models.TimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('imagefile', models.FileField(default='defaultset.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=2000)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.chairman')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(blank=True, default='default.jpg', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeno', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('job_profession', models.CharField(blank=True, max_length=50)),
                ('job_address', models.CharField(blank=True, max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=20)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=30)),
                ('family_member_details', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_by', models.CharField(max_length=50)),
                ('suggestion_title', models.CharField(max_length=50)),
                ('suggestion_desc', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('otp', models.IntegerField(default=459)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('family_contact_no', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.FileField(default='defaultpicw.jpg', upload_to='img/')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.chairman')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_homeno', models.CharField(max_length=20)),
                ('v_name', models.CharField(max_length=50)),
                ('v_mobile_no', models.CharField(max_length=20)),
                ('v_date', models.DateField()),
                ('v_time', models.TimeField()),
                ('reason', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.chairman')),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails')),
                ('mem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.member')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chairman.user')),
                ('main_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.maintenance')),
                ('member_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.member')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.chairman')),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.member')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.member'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.user'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_subject', models.CharField(max_length=50)),
                ('complaint_desc', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.chairman')),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chairman.member')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user')),
            ],
        ),
        migrations.AddField(
            model_name='chairman',
            name='m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.memberdetails'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.user'),
        ),
    ]
